### ISSUE TITLE
Incidencia - Eventos y Sesiones - Campos mal informados en sesiones periódicas

### ISSUE THREAD

**Issue by enricsinergia** [SinergiaTIC/SinergiaCRM#103]
**Descripción del problema**
En #16 se introdujeron unos cambios para inicializar algunos campos de las sesiones creadas de forma periódica, lo que ha provocado que ahora cuando se crean sesiones periódicas si no se rellenan color o descripción, éstos se rellenen con el código de usuario que está haciendo la operación.

**Cómo reproducir el problema**
1. Escoger un evento
2. Ir a creación de sesiones periódicas
3. Generar sesiones periódicas sin haber introducido color ni descripción
4. Comprobar que los campos color y descripción tienen el código del usuario que ha realizado la creación

**Comportamiento esperado**
En caso de no especificarse color ni descripción, el color debería copiarse del evento (creo que esto ya era así antes) y la descripción.... no tengo claro si copiaría la del evento o la dejaría en blanco (probablemente lo primero).

**Solución propuesta**
Revisar el código de stic_Events/Utils.php función createPeriodicSessions líneas 318 en adelante para no asignar el id de usuario si no hay dato.

**Comment by jalbaiges** [comment]
La herencia de datos entre evento y sesiones debería ser consistente independientemente de la vía usada para crear una sesión (vista de edición o asistente de creación de sesiones periódicas).
