### ISSUE TITLE
Incidencia - Actividades - Tareas no se actualiza en el calendario de Google

### ISSUE THREAD

**Issue by PaulaaSTIC** [SinergiaTIC/SinergiaCRM#110]
**Descripción del problema**

Al realizar una sincronización con el calendario de Google a través de iCal, se visualizan todas las actividades del calendario, a excepción de las tareas.

**Cómo reproducir el problema**

1. Generar una tarea y una reunión.
2. Ir al perfil de usuario.
3. Ir a la pestaña Avanzado y localizar la sección Opciones del calendario.
4. Copiar el Enlace de integración iCal.
5. Ir a Google Calendar y en la columna izquierda, desplegar el menú junto a la etiqueta "Otros calendarios".
6. Pulsar en "Añadir por URL" y pegar la dirección copiada en el CRM.
7. Comprobar que se visualizan las reuniones pero no las tareas.

**Comportamiento esperado**

Las tareas deberían visualizarse del mismo modo que las reuniones.

**Comment by ManuSinergiaCRM** [comment]
Buenas, no lo he encontrado en la documentación oficial de Google Calendar pero preguntando a ChatGPT indica lo siguiente:

> Para importar y sincronizar correctamente un archivo iCal que contiene tareas en Google Calendar, hay que entender que Google Calendar maneja los eventos y las tareas de manera diferente. El problema principal con el archivo que proporcionaste es que contiene tareas (VTODO), y Google Calendar no soporta de manera nativa la importación de tareas desde archivos iCal. Google Calendar solo admite la importación de eventos (VEVENT).
> Solución: Convertir Tareas en Eventos
> Una solución efectiva para este problema es convertir las tareas (VTODO) en eventos (VEVENT), ya que Google Calendar no soporta tareas directamente desde archivos iCal
> 

En SuiteCRM existe el siguiente código (https://github.com/SinergiaTIC/SinergiaCRM/blob/develop/modules/iCals/iCal.php#L233-L236) 
que permite indicar de forma dinámica si queremos generar el archivo iCal con las tareas como eventos (VEVENT) o como tareas (VTODO). 

Por defecto, el enlace de integración de iCal se genera sin este parámetro por lo que la solución más sencilla sería agregar manualmente dicho parámetro a la URL generada por el CRM en el paso de crear el calendario en Google desde la URL.

- http://<DOMINIO>/ical_server.php?type=ics&key=<CLAVE>&email=<EMAIL>**&show_tasks_as_events=true**


Puede haber otras herramientas como Outlook donde queramos sincronizar el calendario de sinergiaCRM que sí entiendan las directivas **VTODO** por lo que no modificaría el enlace iCal que genera el CRM al introducir una clave de Publicación y sí documentaría que para Google Calendar es necesario añadir el parámetro anterior.

- Solo una duda a resolver con Alberto, además de documentarlo en la wiki, ¿lo indicamos en el tooltip del enlace de integración de iCal?

**Comment by e-deni** [comment]
Incorporada en wiki esa nota temporal sobre la alternativa de agregar el parámetro https://wikisuite.sinergiacrm.org/index.php?title=Actividades_y_Calendario#Ver_el_calendario_del_CRM_en_Google_Calendar
Eliminar cuando se despliegue el PR
