### ISSUE TITLE
Incidencia - Economía - Problema de generación de archivo en remesa debido a caracteres en blanco en mandato

### ISSUE THREAD

**Issue by juanSTIC** [SinergiaTIC/SinergiaCRM#149]
**Descripción del problema:**
Se ha observado que al incluir un pago con un mandato que contiene algún espacio en blanco en una remesa, al generar esta, el archivo no se genera debido a que la librería SEPA utilizada no admite caracteres en blanco en este campo (https://github.com/SinergiaTIC/SinergiaCRM/blob/develop/SticInclude/vendor/sepaDebits/class.SEPADirectDebitTransaction.php#L183-L197). Sin embargo, el usuario no recibe notificación de este error, lo que dificulta su detección y corrección. Dado que el campo del mandato se genera automáticamente de manera correcta si se deja en blanco, este error puede aparecer cuando se edita manualmente o en escenarios en los que el mandato se crea vía importación u otro mecanismo.

Cabe investigar más a fondo si se debería admitir el espacio en blanco como carácter válido, como se ha visto en alguna documentación.

**Cómo reproducir el problema:**
1. En un pago de tipo domiciliación, modifica el mandato (vía base de datos) introduciendo algún espacio en blanco.
2. Incluye el pago en una remesa de domiciliaciones.
3. Genera el archivo de la remesa y verifica que el sistema se queda en espera sin devolver el control al usuario, además de no generar el archivo XML.

**Comportamiento esperado:**
Si realmente el carácter espacio no debe ser admitido, el usuario debe ser avisado mediante el log de la propia remesa que aparece en pantalla, como ya ocurre con otros errores.

**Solución propuesta:**
En función de lo investigado:
- Modificar la librería para que admita el espacio como carácter válido.
- Añadir un log informativo en la remesa y modificar el código para que finalice el proceso.

**Comment by jalbaiges** [comment]
En su momento ya se introdujo una validación relativa al mandato que generaba el mismo efecto cuando su longitud excedía de 35 caracteres (https://github.com/SinergiaTIC/SinergiaCRM/blob/develop/modules/stic_Remittances/GenerateSEPADirectDebits.php#L197). Este mismo problema se produce también, por ejemplo, cuando el campo relativo al nombre de la entidad supera los 70 caracteres. Estaría bien que el issue analizara y resolviera los diferentes casos de naturaleza similar que puedan darse.

**Comment by juanSTIC** [comment]
resuelto en el PR #150
