### ISSUE TITLE
Mejora - Home/Inicio - Agregar Dashlet Kreports

### ISSUE THREAD

**Issue by ainaraRT** [SinergiaTIC/SinergiaCRM#340]
**¿Está tu propuesta relacionada con algún problema o falta de funcionalidad?**

Se ha comprobado que al introducir directamente la URL del informe de Kreports en la pestaña de web en “Agregar Dashlet”, que era lo que antes dejaba, aparece el siguiente error:

![image](https://github.com/user-attachments/assets/3fd9e33a-df2d-4321-a801-68821f4fcd87)

**Descripción de la propuesta**

Se propone crear un Dashlet de Kreports donde se pueda seleccionar un informe.

**Información adicional**

Se investigó y se comprobó que no funciona desde un cambio en el core de SuiteCRM.

**Comment by ainaraRT** [comment]
Commit del core de SuiteCRM: https://github.com/salesagility/SuiteCRM/commit/34d2745279d176af9ca578851d96e75f9155c951#r131619664

**Comment by AlbertoSTIC** [comment]
Duplicado: https://github.com/SinergiaTIC/SinergiaCRM/issues/261
