### ISSUE TITLE
Incidencia - Encuestas - Múltiples envíos de respuesta a encuesta al accionar el botón de envío repetidamente

### ISSUE THREAD

**Issue by jordiSTIC** [SinergiaTIC/SinergiaCRM#489]
## Descripción del problema
En cualquier formulario de respuesta a una encuesta, se envían tantas respuestas como clics seamos capaces de hacer al submit correspondiente, antes de la redirección habitual. Visto también en suitecrm.sinergiacrm.org

## Cómo reproducir el problema
1. Crear una encuesta y hacerla pública
2. Acceder al link de la encuesta, responderla y presionar repetidamente el botón "submit"
3. En el crm, en la encuesta, verificar que tiene tantas respuestas como clicks hemos realizado al botón

## Comportamiento esperado
No se deberían enviar múltiples respuestas

## Solución propuesta
En la definición del formulario de envío de respuesta:
https://github.com/SinergiaTIC/SinergiaCRM/blob/9606cd39784d2af859dde77641b52a3b864dd876/modules/Surveys/Entry/Survey.php#L148-L165

Deshabilitar el botón "submit" en el evento `onsubmit` del formulario (código a verificar):

```html
<form method="post" onsubmit="this.querySelector('button[type="submit"]').disabled = true">
[...]
</form>
```

## Contexto
Se presenta en todas las instancias, incluída la última versión de SuiteCRM

**Comment by SinergiaCRM** [comment]
https://github.com/salesagility/SuiteCRM/issues/10624
