### ISSUE TITLE
Mejora - Remesas - Añadir validación de falta de CdP en Pagos

### ISSUE THREAD

**Issue by AlbertoSTIC** [SinergiaTIC/SinergiaCRM#50]
**¿Está tu propuesta relacionada con algún problema o falta de funcionalidad?**

Actualmente es posible generar remesas que contengan Pagos que no tengan Compromisos de Pagos relacionados. Esta situación provoca que, por equivocación, se puedan pagos duplicados. 

**Descripción de la propuesta**

Se propone añadir una validación en el momento de generar la Remesa, que compruebe que los registros de Pagos asociados contengan siempre una relación con un CdP. 

De la misma manera que ya se hace con la relación de Personas o Organizaciones:
https://github.com/SinergiaTIC/SinergiaCRM/blob/627863e3e4beb6e0c5ad3813a38f6e58cacd11a0/modules/stic_Remittances/GenerateSEPADirectDebits.php#L185-L189

**Información adicional**

**Comment by juanSTIC** [comment]
Esta funcionalidad se añadio en el pr #150 , por lo que se cierra este issue
